////////////////////////////////////////////////////////////////////////////////////////
// This file is part of the U3 SDK: https://github.com/smartlydressedgames/u3-sdk/    //
// Please refer to the included LICENSE.txt for copyright notice and license details. //
////////////////////////////////////////////////////////////////////////////////////////
#if UNITY_STANDALONE_WIN

using System.Runtime.InteropServices;

namespace SDG.Unturned
{
	/// <summary>
	/// Uses the Win32 API to force a console to be created and destroyed.
	/// </summary>
	public static class WindowsConsole
	{
		/// <summary>
		/// Should we manually create and destroy a Win32 console?
		/// Useful for IO on Windows desktop, but not as much for dedicated machines.
		/// </summary>
		private static CommandLineFlag shouldManageConsole = new CommandLineFlag(true, "-NoWin32Console");

		[DllImport("kernel32.dll", SetLastError = true)]
		public static extern bool AllocConsole();

		[DllImport("kernel32.dll", SetLastError = true)]
		public static extern bool FreeConsole();

		[DllImport("kernel32.dll", SetLastError = true)]
		private static extern bool SetConsoleOutputCP(uint wCodePageID);

		[DllImport("kernel32.dll", SetLastError = true)]
		public static extern bool SetConsoleCP(uint wCodePageID);

		/// <summary>
		/// Allocate Windows console if enabled.
		/// </summary>
		public static void conditionalAlloc()
		{
			if (shouldManageConsole)
			{
				bool allocResult = AllocConsole();
				if (allocResult == false)
				{
					int allocErrorCode = Marshal.GetLastWin32Error();
					UnturnedLog.warn("Unable to allocate Windows console: {0}", allocErrorCode);
				}
			}
		}

		/// <summary>
		/// Free Windows console if enabled.
		/// </summary>
		public static void conditionalFree()
		{
			if (shouldManageConsole)
			{
				bool freeResult = FreeConsole();
				if (freeResult == false)
				{
					int freeErrorCode = Marshal.GetLastWin32Error();
					UnturnedLog.warn("Unable to free Windows console: {0}", freeErrorCode);
				}
			}
		}

		public static void setCodePageToUTF8()
		{
			if (shouldManageConsole)
			{
				const uint CP_UTF8 = 65001;

				bool outputResult = SetConsoleOutputCP(CP_UTF8);
				if (outputResult == false)
				{
					int outputErrorCode = Marshal.GetLastWin32Error();
					UnturnedLog.warn("Unable to set Windows console output code page: {0}", outputErrorCode);
				}

				bool inputResult = SetConsoleCP(CP_UTF8);
				if (inputResult == false)
				{
					int inputErrorCode = Marshal.GetLastWin32Error();
					UnturnedLog.warn("Unable to set Windows console input code page: {0}", inputErrorCode);
				}
			}
		}

		public static void RegisterCtrlHandler(System.Action<ECtrlType> callback)
		{
			if (shouldManageConsole)
			{
				ctrlHandlerCallback = callback;
				SetConsoleCtrlHandler(CtrlHandlerRoutine, true);
			}
		}

		[DllImport("WindowsAssertionFix.dll", SetLastError = true)]
		private static extern void disable_assertions();

		private static CommandLineFlag shouldApplyWindowsAssertionExperiment = new CommandLineFlag(false, "-TryDisableAssertions");

		public static void ApplyAssertionExperimentalFix()
		{
			if (shouldManageConsole && shouldApplyWindowsAssertionExperiment)
			{
				disable_assertions();
			}
		}

		private static bool CtrlHandlerRoutine(ECtrlType ctrlType)
		{
			// This routine is called on a separate thread!
			ctrlHandlerCallback?.Invoke(ctrlType);

			// According to documentation the system will wait up to 5000ms by default.
			// https://learn.microsoft.com/en-us/windows/console/handlerroutine
			System.Threading.Thread.Sleep(4000);

			return true;
		}

		private static System.Action<ECtrlType> ctrlHandlerCallback;

		public enum ECtrlType
		{
			/// <summary>
			/// A CTRL+C signal was received, either from keyboard input or from a signal generated by the GenerateConsoleCtrlEvent function.
			/// </summary>
			CTRL_C_EVENT = 0,

			/// <summary>
			/// A CTRL+BREAK signal was received, either from keyboard input or from a signal generated by GenerateConsoleCtrlEvent.
			/// </summary>
			CTRL_BREAK_EVENT = 1,

			/// <summary>
			/// A signal that the system sends to all processes attached to a console when the user closes the console
			/// (either by clicking Close on the console window's window menu, or by clicking the End Task button command from Task Manager).
			/// </summary>
			CTRL_CLOSE_EVENT = 2,

			// Other event types are irrelevant because they are only sent to services.
			// https://learn.microsoft.com/en-us/windows/console/handlerroutine
		}

		private delegate bool HandlerRoutine(ECtrlType ctrlType);

		[DllImport("kernel32.dll")]
		private static extern bool SetConsoleCtrlHandler(HandlerRoutine handlerRoute, bool add);
	}

}
#endif // UNITY_STANDALONE_WIN
